version: '3.8'
services:
  weatherapp_backend:
    container_name: weatherapp_backend
    environment:
      - APPID=f0ecbddd895ef675d968514b4069e073 # Suggestion: Not to add this within the docker-compose file
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    command: npm run-script hot-reload
    volumes:
      - ./backend/src:/usr/src/app/src
      - /backend/node_modules

  weatherapp_frontend:
    container_name: weatherapp_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./frontend/src:/frontend/src
      - /frontend/node_modules
